language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"

matrix:
  allow_failures:
   - node_js: "0.12" # will remove this once xcli upgrades streamline depedency to the latest

install:
  - npm install -g npm@1.4.23
  - npm --version
  - npm install
  